### ISSUE TITLE
Cannot normalize image because contours are not correctly computed/loaded

### ISSUE THREAD

**Issue by BartlomiejGasyna** [Ekberjan/Iris-Verification#2]
[OpenCV 4.4.0, Nvdia Jetson Nano 4GB]

I've tried to implement Your repository, with included test images, but I have encountered significant error that I cannot pass, it is in pirProcessing.cpp -> segment() function where it does not seem to be working, part of the code with debug info:
`
		
		//Start Processing
		// Locate the pupil
		detectPupil(pSrc, rPupil, minPupilDiameter, maxPupilDiameter);

		// Fill the holes in an area surrounding pupil
		cv::Mat clone_src = pSrc.clone();
		// select a ROI	
		cv::Rect mRoi = cv::Rect(rPupil.getCenter().x - 3.0 / 4.0 * maxIrisDiameter / 2.0,
			rPupil.getCenter().y - 3.0 / 4.0*maxIrisDiameter / 2.0,
			3.0 / 4.0*maxIrisDiameter,
			3.0 / 4.0*maxIrisDiameter);
		std::cout << "mRoi: " << mRoi.size() << std::endl;
		std::cout << "clone_src: " << clone_src.size() << std::endl;

		
		try
		{
		cv::Mat clone_src2 = clone_src(mRoi).clone(); // this is source of error
		fillWhiteHoles(clone_src2, clone_src2);
		clone_src2.copyTo(clone_src(mRoi));
		}
		catch (const std::exception& e)
		{
			std::cout << e.what();
		}`
My output is as follows:
```

================
Start processing ... 
================

mRoi: 210, [210 x 210]
clone_src: [640 x 480]
OpenCV(4.1.1) /home/nvidia/host/build_opencv/nv_opencv/modules/core/src/matrix.cpp:466: error: (-215:Assertion failed) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function 'Mat'
std::exception
1           0
Cannot normalize image because contours are not correctly computed/loaded

====================
End processing. 
====================```

To clarify - I've been using included images - "1.jpg" and "2.jpg", with default Gabor filter and image points, could you please try to help this? If need I could also upload zip file..

Thanks in advance

**Comment by sunnythree** [comment]
in the detectPupil function:
```             
                cv::Mat gh = cv::Mat(filled.size(), CV_32FC1);
		cv::Sobel(filled, gh, CV_32FC1, 1, 0);

		// Gradients in vertical direction
		cv::Mat gv = cv::Mat(filled.size(), CV_32FC1);
		cv::Sobel(filled, gv, CV_32FC1, 0, 1);

		// Normalize gradients
		cv::Mat gh2 = cv::Mat(filled.size(), CV_32FC1);
		cv::multiply(gh, gh, gh2);

		cv::Mat gv2 = cv::Mat(filled.size(), CV_32FC1);
		cv::multiply(gv, gv, gv2);

		cv::Mat gn = cv::Mat(filled.size(), CV_32FC1);
		cv::add(gh2, gv2, gn);
		**gn = gn + 0.00001;**
		gn.convertTo(gn, CV_32FC1);
		cv::pow(gn, 0.5, gn);
		cv::divide(gh, gn, gh, 1, CV_32FC1);
		cv::divide(gv, gn, gv, 1, CV_32FC1);
```	
		
		
		some of elements of gn maybe zero, cv::divide zero pruduce inf data:
		one of solutions is add a very small float value, such as 0.00001 for gn Mat. or set zeroes of gn Mat to a small non-zero value;
